FROM node:10 as build-step
WORKDIR /app
COPY package*.json  ./
RUN npm install
COPY . ./
RUN npm run build

#nginx set up
FROM nginx:latest as prod-stage
COPY --from=build-step /app/dist/angularDocker  /usr/share/nginx/html
EXPOSE 80
CMD nginx -g 'daemon off;'


 